import '../models/map_point.dart';

class MapService {
  const MapService();

  List<MapPoint> getInitialParaPoints() {
    // Base local inicial para MVP. Coordenadas aproximadas e curadas para
    // distribuir visualmente o mapa pelo Para antes da entrada de backend/API.
    return const [
      MapPoint(
        id: 'hotel-belem-001',
        name: 'Hotel Princesa Louca',
        category: MapPointCategory.hotel,
        latitude: -1.4529,
        longitude: -48.4907,
        city: 'Belem',
        description: 'Hotel tradicional em area central de Belem.',
      ),
      MapPoint(
        id: 'hotel-belem-002',
        name: 'Radisson Maiorana Belem',
        category: MapPointCategory.hotel,
        latitude: -1.4524,
        longitude: -48.4822,
        city: 'Belem',
        description: 'Hospedagem premium na regiao de Nazare.',
      ),
      MapPoint(
        id: 'hotel-santarem-001',
        name: 'Barrudada Tropical Hotel',
        category: MapPointCategory.hotel,
        latitude: -2.4316,
        longitude: -54.7152,
        city: 'Santarem',
        description: 'Hospedagem conhecida para viagens no oeste do Para.',
      ),
      MapPoint(
        id: 'hotel-parauapebas-001',
        name: 'Hotel Vale dos Carajas',
        category: MapPointCategory.hotel,
        latitude: -6.0712,
        longitude: -49.9018,
        city: 'Parauapebas',
        description: 'Hospedagem estrategica na regiao de Carajas.',
      ),
      MapPoint(
        id: 'hotel-salinopolis-001',
        name: 'Hotel Salinas Premium',
        category: MapPointCategory.hotel,
        latitude: -0.6174,
        longitude: -47.3568,
        city: 'Salinopolis',
        description: 'Ponto de hospedagem inicial no litoral paraense.',
      ),
      MapPoint(
        id: 'mercado-belem-001',
        name: 'Mercado Ver-o-Peso',
        category: MapPointCategory.mercado,
        latitude: -1.4522,
        longitude: -48.5034,
        city: 'Belem',
        description: 'Mercado tradicional e ponto cultural do Para.',
      ),
      MapPoint(
        id: 'mercado-belem-002',
        name: 'Feira do Acai',
        category: MapPointCategory.mercado,
        latitude: -1.4498,
        longitude: -48.5046,
        city: 'Belem',
        description: 'Area tradicional de comercio regional em Belem.',
      ),
      MapPoint(
        id: 'mercado-santarem-001',
        name: 'Mercado Municipal de Santarem',
        category: MapPointCategory.mercado,
        latitude: -2.4382,
        longitude: -54.7073,
        city: 'Santarem',
        description: 'Mercado regional proximo a orla de Santarem.',
      ),
      MapPoint(
        id: 'mercado-castanhal-001',
        name: 'Mercado Municipal de Castanhal',
        category: MapPointCategory.mercado,
        latitude: -1.2937,
        longitude: -47.9266,
        city: 'Castanhal',
        description: 'Ponto de comercio central em Castanhal.',
      ),
      MapPoint(
        id: 'mercado-maraba-001',
        name: 'Mercado Municipal de Maraba',
        category: MapPointCategory.mercado,
        latitude: -5.3548,
        longitude: -49.1197,
        city: 'Maraba',
        description: 'Ponto popular de compras e apoio urbano.',
      ),
      MapPoint(
        id: 'posto-belem-001',
        name: 'Posto Batista Campos',
        category: MapPointCategory.posto,
        latitude: -1.4596,
        longitude: -48.4827,
        city: 'Belem',
        description: 'Ponto de abastecimento em area central.',
      ),
      MapPoint(
        id: 'posto-ananindeua-001',
        name: 'Posto BR Ananindeua',
        category: MapPointCategory.posto,
        latitude: -1.3656,
        longitude: -48.3722,
        city: 'Ananindeua',
        description: 'Ponto de apoio na regiao metropolitana de Belem.',
      ),
      MapPoint(
        id: 'posto-altamira-001',
        name: 'Posto Transamazonica',
        category: MapPointCategory.posto,
        latitude: -3.2041,
        longitude: -52.2100,
        city: 'Altamira',
        description: 'Abastecimento estrategico na Transamazonica.',
      ),
      MapPoint(
        id: 'posto-tucurui-001',
        name: 'Posto Tucurui Centro',
        category: MapPointCategory.posto,
        latitude: -3.7659,
        longitude: -49.6792,
        city: 'Tucurui',
        description: 'Ponto de apoio para viagens na regiao do lago.',
      ),
      MapPoint(
        id: 'posto-braganca-001',
        name: 'Posto Braganca Centro',
        category: MapPointCategory.posto,
        latitude: -1.0536,
        longitude: -46.7656,
        city: 'Braganca',
        description: 'Abastecimento em rota para o nordeste paraense.',
      ),
      MapPoint(
        id: 'oficina-belem-001',
        name: 'Oficina Umarizal',
        category: MapPointCategory.oficina,
        latitude: -1.4447,
        longitude: -48.4874,
        city: 'Belem',
        description: 'Oficina cadastrada para suporte ao viajante.',
      ),
      MapPoint(
        id: 'oficina-ananindeua-001',
        name: 'Auto Center Ananindeua',
        category: MapPointCategory.oficina,
        latitude: -1.3650,
        longitude: -48.3810,
        city: 'Ananindeua',
        description: 'Apoio automotivo na regiao metropolitana.',
      ),
      MapPoint(
        id: 'oficina-maraba-001',
        name: 'Auto Center Maraba',
        category: MapPointCategory.oficina,
        latitude: -5.3682,
        longitude: -49.1173,
        city: 'Maraba',
        description: 'Servico automotivo para viajantes no sudeste do Para.',
      ),
      MapPoint(
        id: 'oficina-parauapebas-001',
        name: 'Oficina Carajas',
        category: MapPointCategory.oficina,
        latitude: -6.0675,
        longitude: -49.9022,
        city: 'Parauapebas',
        description: 'Apoio veicular proximo a regiao de Carajas.',
      ),
      MapPoint(
        id: 'oficina-castanhal-001',
        name: 'Oficina Castanhal Centro',
        category: MapPointCategory.oficina,
        latitude: -1.2962,
        longitude: -47.9281,
        city: 'Castanhal',
        description: 'Oficina de apoio na rota nordeste do Para.',
      ),
      MapPoint(
        id: 'restaurante-belem-001',
        name: 'Remanso do Bosque',
        category: MapPointCategory.restaurante,
        latitude: -1.4511,
        longitude: -48.4628,
        city: 'Belem',
        description: 'Restaurante regional de referencia em Belem.',
      ),
      MapPoint(
        id: 'restaurante-belem-002',
        name: 'Lá em Casa',
        category: MapPointCategory.restaurante,
        latitude: -1.4499,
        longitude: -48.5011,
        city: 'Belem',
        description: 'Culinaria paraense em area turistica de Belem.',
      ),
      MapPoint(
        id: 'restaurante-santarem-001',
        name: 'Casa do Saulo Alter',
        category: MapPointCategory.restaurante,
        latitude: -2.5097,
        longitude: -54.9548,
        city: 'Santarem',
        description: 'Experiencia gastronomica proxima a Alter do Chao.',
      ),
      MapPoint(
        id: 'restaurante-maraba-001',
        name: 'Restaurante Tocantins',
        category: MapPointCategory.restaurante,
        latitude: -5.3545,
        longitude: -49.1170,
        city: 'Maraba',
        description: 'Ponto regional para refeicao em Maraba.',
      ),
      MapPoint(
        id: 'restaurante-soure-001',
        name: 'Restaurante Marajoara',
        category: MapPointCategory.restaurante,
        latitude: -0.7167,
        longitude: -48.5233,
        city: 'Soure',
        description: 'Culinaria regional na Ilha do Marajo.',
      ),
      MapPoint(
        id: 'turismo-belem-001',
        name: 'Estacao das Docas',
        category: MapPointCategory.turismo,
        latitude: -1.4494,
        longitude: -48.5012,
        city: 'Belem',
        description: 'Complexo turistico e gastronomico na orla de Belem.',
      ),
      MapPoint(
        id: 'turismo-belem-002',
        name: 'Mangal das Garcas',
        category: MapPointCategory.turismo,
        latitude: -1.4626,
        longitude: -48.5044,
        city: 'Belem',
        description: 'Parque natural e turistico na capital paraense.',
      ),
      MapPoint(
        id: 'turismo-santarem-001',
        name: 'Orla de Santarem',
        category: MapPointCategory.turismo,
        latitude: -2.4385,
        longitude: -54.6996,
        city: 'Santarem',
        description: 'Ponto turistico inicial no oeste do Para.',
      ),
      MapPoint(
        id: 'turismo-santarem-002',
        name: 'Alter do Chao',
        category: MapPointCategory.turismo,
        latitude: -2.5068,
        longitude: -54.9519,
        city: 'Santarem',
        description: 'Distrito turistico conhecido pelas praias do Tapajos.',
      ),
      MapPoint(
        id: 'turismo-salinopolis-001',
        name: 'Praia do Atalaia',
        category: MapPointCategory.turismo,
        latitude: -0.5896,
        longitude: -47.3051,
        city: 'Salinopolis',
        description: 'Destino de praia no litoral paraense.',
      ),
      MapPoint(
        id: 'turismo-soure-001',
        name: 'Praia do Pesqueiro',
        category: MapPointCategory.turismo,
        latitude: -0.6646,
        longitude: -48.5085,
        city: 'Soure',
        description: 'Praia tradicional na Ilha do Marajo.',
      ),
      MapPoint(
        id: 'hospital-belem-001',
        name: 'Hospital Ophir Loyola',
        category: MapPointCategory.hospital,
        latitude: -1.4589,
        longitude: -48.4809,
        city: 'Belem',
        description: 'Unidade hospitalar de referencia em Belem.',
      ),
      MapPoint(
        id: 'hospital-ananindeua-001',
        name: 'Hospital Metropolitano',
        category: MapPointCategory.hospital,
        latitude: -1.3690,
        longitude: -48.3916,
        city: 'Ananindeua',
        description: 'Hospital de referencia na regiao metropolitana.',
      ),
      MapPoint(
        id: 'hospital-santarem-001',
        name: 'Hospital Regional do Baixo Amazonas',
        category: MapPointCategory.hospital,
        latitude: -2.4430,
        longitude: -54.7308,
        city: 'Santarem',
        description: 'Unidade regional importante no oeste do Para.',
      ),
      MapPoint(
        id: 'hospital-maraba-001',
        name: 'Hospital Regional de Maraba',
        category: MapPointCategory.hospital,
        latitude: -5.3646,
        longitude: -49.1157,
        city: 'Maraba',
        description: 'Referencia hospitalar no sudeste do Para.',
      ),
      MapPoint(
        id: 'hospital-altamira-001',
        name: 'Hospital Regional da Transamazonica',
        category: MapPointCategory.hospital,
        latitude: -3.2033,
        longitude: -52.2087,
        city: 'Altamira',
        description: 'Unidade regional em area estrategica da Transamazonica.',
      ),
      MapPoint(
        id: 'farmacia-belem-001',
        name: 'Farmacia Nazare',
        category: MapPointCategory.farmacia,
        latitude: -1.4529,
        longitude: -48.4812,
        city: 'Belem',
        description: 'Farmacia cadastrada para apoio ao viajante.',
      ),
      MapPoint(
        id: 'farmacia-ananindeua-001',
        name: 'Farmacia Cidade Nova',
        category: MapPointCategory.farmacia,
        latitude: -1.3607,
        longitude: -48.3789,
        city: 'Ananindeua',
        description: 'Apoio farmaceutico na regiao metropolitana.',
      ),
      MapPoint(
        id: 'farmacia-santarem-001',
        name: 'Farmacia Centro Santarem',
        category: MapPointCategory.farmacia,
        latitude: -2.4389,
        longitude: -54.7008,
        city: 'Santarem',
        description: 'Ponto de apoio no centro de Santarem.',
      ),
      MapPoint(
        id: 'farmacia-maraba-001',
        name: 'Farmacia Nova Maraba',
        category: MapPointCategory.farmacia,
        latitude: -5.3635,
        longitude: -49.1179,
        city: 'Maraba',
        description: 'Apoio farmaceutico em Maraba.',
      ),
      MapPoint(
        id: 'farmacia-breves-001',
        name: 'Farmacia Breves Centro',
        category: MapPointCategory.farmacia,
        latitude: -1.6804,
        longitude: -50.4809,
        city: 'Breves',
        description: 'Ponto de saude e apoio no Marajo ocidental.',
      ),
      MapPoint(
        id: 'pets-belem-001',
        name: 'Pet Care Belem',
        category: MapPointCategory.pets,
        latitude: -1.4417,
        longitude: -48.4684,
        city: 'Belem',
        description: 'Servico pet selecionado para viajantes com animais.',
      ),
      MapPoint(
        id: 'pets-ananindeua-001',
        name: 'Pet Shop Ananindeua',
        category: MapPointCategory.pets,
        latitude: -1.3659,
        longitude: -48.3728,
        city: 'Ananindeua',
        description: 'Apoio pet na regiao metropolitana.',
      ),
      MapPoint(
        id: 'pets-castanhal-001',
        name: 'Pet Center Castanhal',
        category: MapPointCategory.pets,
        latitude: -1.2945,
        longitude: -47.9277,
        city: 'Castanhal',
        description: 'Servico pet em rota de viagem pelo nordeste paraense.',
      ),
      MapPoint(
        id: 'pets-parauapebas-001',
        name: 'Pet Center Parauapebas',
        category: MapPointCategory.pets,
        latitude: -6.0668,
        longitude: -49.9040,
        city: 'Parauapebas',
        description: 'Apoio para viajantes com animais em Carajas.',
      ),
      MapPoint(
        id: 'pets-salinopolis-001',
        name: 'Pet Salinas',
        category: MapPointCategory.pets,
        latitude: -0.6136,
        longitude: -47.3561,
        city: 'Salinopolis',
        description: 'Servico pet inicial no litoral paraense.',
      ),
      MapPoint(
        id: 'hotel-altamira-001',
        name: 'Hotel Xingu Altamira',
        category: MapPointCategory.hotel,
        latitude: -3.2041,
        longitude: -52.2100,
        city: 'Altamira',
        description: 'Hospedagem de apoio na regiao do Xingu.',
      ),
      MapPoint(
        id: 'hotel-barcarena-001',
        name: 'Hotel Barcarena Centro',
        category: MapPointCategory.hotel,
        latitude: -1.5060,
        longitude: -48.6258,
        city: 'Barcarena',
        description: 'Hospedagem estrategica para viagens pela regiao portuaria.',
      ),
      MapPoint(
        id: 'hotel-breves-001',
        name: 'Hotel Marajo Breves',
        category: MapPointCategory.hotel,
        latitude: -1.6822,
        longitude: -50.4803,
        city: 'Breves',
        description: 'Hospedagem no Marajo ocidental.',
      ),
      MapPoint(
        id: 'hotel-itaituba-001',
        name: 'Hotel Tapajos Itaituba',
        category: MapPointCategory.hotel,
        latitude: -4.2761,
        longitude: -55.9836,
        city: 'Itaituba',
        description: 'Base de hospedagem no Tapajos.',
      ),
      MapPoint(
        id: 'hotel-redencao-001',
        name: 'Hotel Redencao Palace',
        category: MapPointCategory.hotel,
        latitude: -8.0253,
        longitude: -50.0317,
        city: 'Redencao',
        description: 'Hospedagem no sul do Para.',
      ),
      MapPoint(
        id: 'hotel-oriximina-001',
        name: 'Hotel Oriximina Centro',
        category: MapPointCategory.hotel,
        latitude: -1.7656,
        longitude: -55.8661,
        city: 'Oriximina',
        description: 'Ponto de estadia no Baixo Amazonas.',
      ),
      MapPoint(
        id: 'mercado-abaetetuba-001',
        name: 'Mercado Municipal de Abaetetuba',
        category: MapPointCategory.mercado,
        latitude: -1.7181,
        longitude: -48.8828,
        city: 'Abaetetuba',
        description: 'Mercado regional em cidade ribeirinha do Para.',
      ),
      MapPoint(
        id: 'mercado-cameta-001',
        name: 'Mercado Municipal de Cameta',
        category: MapPointCategory.mercado,
        latitude: -2.2444,
        longitude: -49.4958,
        city: 'Cameta',
        description: 'Comercio tradicional no Baixo Tocantins.',
      ),
      MapPoint(
        id: 'mercado-capanema-001',
        name: 'Mercado Municipal de Capanema',
        category: MapPointCategory.mercado,
        latitude: -1.1958,
        longitude: -47.1808,
        city: 'Capanema',
        description: 'Ponto de comercio no nordeste paraense.',
      ),
      MapPoint(
        id: 'mercado-obidos-001',
        name: 'Mercado Municipal de Obidos',
        category: MapPointCategory.mercado,
        latitude: -1.9178,
        longitude: -55.5181,
        city: 'Obidos',
        description: 'Mercado ribeirinho no Baixo Amazonas.',
      ),
      MapPoint(
        id: 'mercado-monte-alegre-001',
        name: 'Mercado Municipal de Monte Alegre',
        category: MapPointCategory.mercado,
        latitude: -2.0008,
        longitude: -54.0810,
        city: 'Monte Alegre',
        description: 'Ponto de compras e apoio regional.',
      ),
      MapPoint(
        id: 'mercado-afua-001',
        name: 'Mercado Municipal de Afua',
        category: MapPointCategory.mercado,
        latitude: -0.1567,
        longitude: -50.3861,
        city: 'Afua',
        description: 'Mercado ribeirinho na regiao do Marajo.',
      ),
      MapPoint(
        id: 'posto-moju-001',
        name: 'Posto Moju Centro',
        category: MapPointCategory.posto,
        latitude: -1.8839,
        longitude: -48.7689,
        city: 'Moju',
        description: 'Abastecimento em rota do Baixo Tocantins.',
      ),
      MapPoint(
        id: 'posto-tailandia-001',
        name: 'Posto Tailandia Centro',
        category: MapPointCategory.posto,
        latitude: -2.9450,
        longitude: -48.9489,
        city: 'Tailandia',
        description: 'Apoio para deslocamentos no nordeste do Para.',
      ),
      MapPoint(
        id: 'posto-itaituba-001',
        name: 'Posto Tapajos Itaituba',
        category: MapPointCategory.posto,
        latitude: -4.2758,
        longitude: -55.9838,
        city: 'Itaituba',
        description: 'Abastecimento estrategico na regiao do Tapajos.',
      ),
      MapPoint(
        id: 'posto-redencao-001',
        name: 'Posto Redencao Sul',
        category: MapPointCategory.posto,
        latitude: -8.0260,
        longitude: -50.0311,
        city: 'Redencao',
        description: 'Ponto de apoio rodoviario no sul paraense.',
      ),
      MapPoint(
        id: 'posto-xinguara-001',
        name: 'Posto Xinguara Centro',
        category: MapPointCategory.posto,
        latitude: -7.0983,
        longitude: -49.9439,
        city: 'Xinguara',
        description: 'Abastecimento na rota sul do Para.',
      ),
      MapPoint(
        id: 'posto-conceicao-001',
        name: 'Posto Araguaia',
        category: MapPointCategory.posto,
        latitude: -8.2644,
        longitude: -49.2697,
        city: 'Conceicao do Araguaia',
        description: 'Apoio de viagem proximo ao rio Araguaia.',
      ),
      MapPoint(
        id: 'oficina-abaetetuba-001',
        name: 'Auto Center Abaetetuba',
        category: MapPointCategory.oficina,
        latitude: -1.7190,
        longitude: -48.8835,
        city: 'Abaetetuba',
        description: 'Suporte automotivo no Baixo Tocantins.',
      ),
      MapPoint(
        id: 'oficina-barcarena-001',
        name: 'Oficina Barcarena',
        category: MapPointCategory.oficina,
        latitude: -1.5052,
        longitude: -48.6249,
        city: 'Barcarena',
        description: 'Oficina para apoio local e rodoviario.',
      ),
      MapPoint(
        id: 'oficina-itaituba-001',
        name: 'Oficina Tapajos',
        category: MapPointCategory.oficina,
        latitude: -4.2768,
        longitude: -55.9822,
        city: 'Itaituba',
        description: 'Apoio automotivo no oeste do Para.',
      ),
      MapPoint(
        id: 'oficina-redencao-001',
        name: 'Auto Center Redencao',
        category: MapPointCategory.oficina,
        latitude: -8.0244,
        longitude: -50.0324,
        city: 'Redencao',
        description: 'Servico automotivo para viajantes no sul do estado.',
      ),
      MapPoint(
        id: 'oficina-xinguara-001',
        name: 'Oficina Xinguara',
        category: MapPointCategory.oficina,
        latitude: -7.0978,
        longitude: -49.9444,
        city: 'Xinguara',
        description: 'Apoio veicular na regiao sul paraense.',
      ),
      MapPoint(
        id: 'oficina-tucurui-001',
        name: 'Auto Center Tucurui',
        category: MapPointCategory.oficina,
        latitude: -3.7652,
        longitude: -49.6778,
        city: 'Tucurui',
        description: 'Suporte automotivo na regiao do lago de Tucurui.',
      ),
      MapPoint(
        id: 'restaurante-abaetetuba-001',
        name: 'Restaurante Beira Rio Abaetetuba',
        category: MapPointCategory.restaurante,
        latitude: -1.7174,
        longitude: -48.8844,
        city: 'Abaetetuba',
        description: 'Culinaria regional em cidade ribeirinha.',
      ),
      MapPoint(
        id: 'restaurante-braganca-001',
        name: 'Restaurante Caete',
        category: MapPointCategory.restaurante,
        latitude: -1.0536,
        longitude: -46.7656,
        city: 'Braganca',
        description: 'Ponto de comida regional no nordeste paraense.',
      ),
      MapPoint(
        id: 'restaurante-cameta-001',
        name: 'Restaurante Tocantins Cameta',
        category: MapPointCategory.restaurante,
        latitude: -2.2440,
        longitude: -49.4950,
        city: 'Cameta',
        description: 'Experiencia simples de culinaria local.',
      ),
      MapPoint(
        id: 'restaurante-obidos-001',
        name: 'Restaurante Forte Obidos',
        category: MapPointCategory.restaurante,
        latitude: -1.9173,
        longitude: -55.5175,
        city: 'Obidos',
        description: 'Ponto regional no Baixo Amazonas.',
      ),
      MapPoint(
        id: 'restaurante-redencao-001',
        name: 'Restaurante Sul do Para',
        category: MapPointCategory.restaurante,
        latitude: -8.0258,
        longitude: -50.0308,
        city: 'Redencao',
        description: 'Restaurante de apoio para rotas do sul paraense.',
      ),
      MapPoint(
        id: 'restaurante-vigia-001',
        name: 'Restaurante Vigia Atlantico',
        category: MapPointCategory.restaurante,
        latitude: -0.8583,
        longitude: -48.1417,
        city: 'Vigia',
        description: 'Ponto gastronomico proximo ao litoral paraense.',
      ),
      MapPoint(
        id: 'turismo-braganca-001',
        name: 'Praia de Ajuruteua',
        category: MapPointCategory.turismo,
        latitude: -0.8310,
        longitude: -46.6030,
        city: 'Braganca',
        description: 'Destino de praia no nordeste paraense.',
      ),
      MapPoint(
        id: 'turismo-cameta-001',
        name: 'Orla de Cameta',
        category: MapPointCategory.turismo,
        latitude: -2.2448,
        longitude: -49.4948,
        city: 'Cameta',
        description: 'Orla historica no Baixo Tocantins.',
      ),
      MapPoint(
        id: 'turismo-tucurui-001',
        name: 'Lago de Tucurui',
        category: MapPointCategory.turismo,
        latitude: -3.7659,
        longitude: -49.6792,
        city: 'Tucurui',
        description: 'Regiao turistica ligada ao lago e a usina.',
      ),
      MapPoint(
        id: 'turismo-monte-alegre-001',
        name: 'Parque Estadual Monte Alegre',
        category: MapPointCategory.turismo,
        latitude: -2.0070,
        longitude: -54.0840,
        city: 'Monte Alegre',
        description: 'Area conhecida por paisagens naturais e arqueologia.',
      ),
      MapPoint(
        id: 'turismo-obidos-001',
        name: 'Forte de Obidos',
        category: MapPointCategory.turismo,
        latitude: -1.9178,
        longitude: -55.5181,
        city: 'Obidos',
        description: 'Ponto historico as margens do Amazonas.',
      ),
      MapPoint(
        id: 'turismo-salvaterra-001',
        name: 'Praia Grande de Salvaterra',
        category: MapPointCategory.turismo,
        latitude: -0.7586,
        longitude: -48.5136,
        city: 'Salvaterra',
        description: 'Destino de praia na Ilha do Marajo.',
      ),
      MapPoint(
        id: 'hospital-cameta-001',
        name: 'Hospital Regional de Cameta',
        category: MapPointCategory.hospital,
        latitude: -2.2446,
        longitude: -49.4962,
        city: 'Cameta',
        description: 'Ponto de saude no Baixo Tocantins.',
      ),
      MapPoint(
        id: 'hospital-itaituba-001',
        name: 'Hospital Regional do Tapajos',
        category: MapPointCategory.hospital,
        latitude: -4.2761,
        longitude: -55.9836,
        city: 'Itaituba',
        description: 'Referencia regional no oeste do Para.',
      ),
      MapPoint(
        id: 'hospital-redencao-001',
        name: 'Hospital Regional Publico do Araguaia',
        category: MapPointCategory.hospital,
        latitude: -8.0253,
        longitude: -50.0317,
        city: 'Redencao',
        description: 'Apoio hospitalar no sul paraense.',
      ),
      MapPoint(
        id: 'hospital-tucurui-001',
        name: 'Hospital Regional de Tucurui',
        category: MapPointCategory.hospital,
        latitude: -3.7654,
        longitude: -49.6787,
        city: 'Tucurui',
        description: 'Unidade regional na area do lago.',
      ),
      MapPoint(
        id: 'hospital-oriximina-001',
        name: 'Hospital Municipal de Oriximina',
        category: MapPointCategory.hospital,
        latitude: -1.7656,
        longitude: -55.8661,
        city: 'Oriximina',
        description: 'Apoio de saude no Baixo Amazonas.',
      ),
      MapPoint(
        id: 'hospital-soure-001',
        name: 'Hospital Municipal de Soure',
        category: MapPointCategory.hospital,
        latitude: -0.7167,
        longitude: -48.5233,
        city: 'Soure',
        description: 'Atendimento inicial na Ilha do Marajo.',
      ),
      MapPoint(
        id: 'farmacia-abaetetuba-001',
        name: 'Farmacia Abaetetuba Centro',
        category: MapPointCategory.farmacia,
        latitude: -1.7185,
        longitude: -48.8832,
        city: 'Abaetetuba',
        description: 'Apoio farmaceutico no Baixo Tocantins.',
      ),
      MapPoint(
        id: 'farmacia-braganca-001',
        name: 'Farmacia Braganca Centro',
        category: MapPointCategory.farmacia,
        latitude: -1.0534,
        longitude: -46.7652,
        city: 'Braganca',
        description: 'Ponto de apoio no nordeste paraense.',
      ),
      MapPoint(
        id: 'farmacia-capanema-001',
        name: 'Farmacia Capanema Centro',
        category: MapPointCategory.farmacia,
        latitude: -1.1958,
        longitude: -47.1808,
        city: 'Capanema',
        description: 'Farmacia de apoio em rota regional.',
      ),
      MapPoint(
        id: 'farmacia-itaituba-001',
        name: 'Farmacia Itaituba Centro',
        category: MapPointCategory.farmacia,
        latitude: -4.2765,
        longitude: -55.9826,
        city: 'Itaituba',
        description: 'Apoio farmaceutico no Tapajos.',
      ),
      MapPoint(
        id: 'farmacia-redencao-001',
        name: 'Farmacia Redencao Centro',
        category: MapPointCategory.farmacia,
        latitude: -8.0250,
        longitude: -50.0320,
        city: 'Redencao',
        description: 'Apoio farmaceutico no sul do Para.',
      ),
      MapPoint(
        id: 'farmacia-vigia-001',
        name: 'Farmacia Vigia Centro',
        category: MapPointCategory.farmacia,
        latitude: -0.8580,
        longitude: -48.1414,
        city: 'Vigia',
        description: 'Apoio de saude no litoral paraense.',
      ),
      MapPoint(
        id: 'pets-abaetetuba-001',
        name: 'Pet Abaetetuba',
        category: MapPointCategory.pets,
        latitude: -1.7194,
        longitude: -48.8824,
        city: 'Abaetetuba',
        description: 'Servico pet em cidade ribeirinha.',
      ),
      MapPoint(
        id: 'pets-braganca-001',
        name: 'Pet Braganca',
        category: MapPointCategory.pets,
        latitude: -1.0540,
        longitude: -46.7660,
        city: 'Braganca',
        description: 'Apoio pet no nordeste do Para.',
      ),
      MapPoint(
        id: 'pets-itaituba-001',
        name: 'Pet Tapajos',
        category: MapPointCategory.pets,
        latitude: -4.2752,
        longitude: -55.9840,
        city: 'Itaituba',
        description: 'Servico pet no oeste paraense.',
      ),
      MapPoint(
        id: 'pets-redencao-001',
        name: 'Pet Redencao',
        category: MapPointCategory.pets,
        latitude: -8.0261,
        longitude: -50.0309,
        city: 'Redencao',
        description: 'Apoio para viajantes com animais no sul do estado.',
      ),
      MapPoint(
        id: 'pets-salvaterra-001',
        name: 'Pet Salvaterra',
        category: MapPointCategory.pets,
        latitude: -0.7580,
        longitude: -48.5142,
        city: 'Salvaterra',
        description: 'Servico pet inicial na Ilha do Marajo.',
      ),
      MapPoint(
        id: 'pets-tucurui-001',
        name: 'Pet Tucurui',
        category: MapPointCategory.pets,
        latitude: -3.7664,
        longitude: -49.6784,
        city: 'Tucurui',
        description: 'Apoio pet na regiao do lago de Tucurui.',
      ),
    ];
  }
}
